/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SubscriptionCallbackRouteImport } from './routes/subscription.callback'
import { Route as SellerWalletRouteImport } from './routes/seller.wallet'
import { Route as SellerSubscriptionRouteImport } from './routes/seller.subscription'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as SellerProductsIndexRouteImport } from './routes/seller.products.index'
import { Route as SellerOrdersIndexRouteImport } from './routes/seller.orders.index'
import { Route as SellerProductsNewRouteImport } from './routes/seller.products.new'
import { Route as SellerProductsIdRouteImport } from './routes/seller.products.$id'
import { Route as SellerOrdersIdRouteImport } from './routes/seller.orders.$id'
import { Route as OrdersStatusIdRouteImport } from './routes/orders.status.$id'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SubscriptionCallbackRoute = SubscriptionCallbackRouteImport.update({
  id: '/subscription/callback',
  path: '/subscription/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerWalletRoute = SellerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSubscriptionRoute = SellerSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SellerRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const SellerProductsIndexRoute = SellerProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersIndexRoute = SellerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsNewRoute = SellerProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsIdRoute = SellerProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersIdRoute = SellerOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => SellerRoute,
} as any)
const OrdersStatusIdRoute = OrdersStatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/search': typeof SearchRoute
  '/seller': typeof SellerRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/subscription': typeof SellerSubscriptionRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/subscription/callback': typeof SubscriptionCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/orders/status/$id': typeof OrdersStatusIdRoute
  '/seller/orders/$id': typeof SellerOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/orders/': typeof SellerOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/subscription': typeof SellerSubscriptionRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/subscription/callback': typeof SubscriptionCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/seller': typeof SellerIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/orders/status/$id': typeof OrdersStatusIdRoute
  '/seller/orders/$id': typeof SellerOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/orders': typeof SellerOrdersIndexRoute
  '/seller/products': typeof SellerProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/search': typeof SearchRoute
  '/seller': typeof SellerRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/products/$id': typeof ProductsIdRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/subscription': typeof SellerSubscriptionRoute
  '/seller/wallet': typeof SellerWalletRoute
  '/subscription/callback': typeof SubscriptionCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/orders/status/$id': typeof OrdersStatusIdRoute
  '/seller/orders/$id': typeof SellerOrdersIdRoute
  '/seller/products/$id': typeof SellerProductsIdRoute
  '/seller/products/new': typeof SellerProductsNewRoute
  '/seller/orders/': typeof SellerOrdersIndexRoute
  '/seller/products/': typeof SellerProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/inbox'
    | '/login'
    | '/orders'
    | '/search'
    | '/seller'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/withdrawals'
    | '/orders/$id'
    | '/payment/callback'
    | '/products/$id'
    | '/seller/profile'
    | '/seller/subscription'
    | '/seller/wallet'
    | '/subscription/callback'
    | '/admin/'
    | '/orders/'
    | '/seller/'
    | '/api/public/paystack-webhook'
    | '/orders/status/$id'
    | '/seller/orders/$id'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/seller/orders/'
    | '/seller/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/inbox'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/withdrawals'
    | '/orders/$id'
    | '/payment/callback'
    | '/products/$id'
    | '/seller/profile'
    | '/seller/subscription'
    | '/seller/wallet'
    | '/subscription/callback'
    | '/admin'
    | '/orders'
    | '/seller'
    | '/api/public/paystack-webhook'
    | '/orders/status/$id'
    | '/seller/orders/$id'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/seller/orders'
    | '/seller/products'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/inbox'
    | '/login'
    | '/orders'
    | '/search'
    | '/seller'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/admin/withdrawals'
    | '/orders/$id'
    | '/payment/callback'
    | '/products/$id'
    | '/seller/profile'
    | '/seller/subscription'
    | '/seller/wallet'
    | '/subscription/callback'
    | '/admin/'
    | '/orders/'
    | '/seller/'
    | '/api/public/paystack-webhook'
    | '/orders/status/$id'
    | '/seller/orders/$id'
    | '/seller/products/$id'
    | '/seller/products/new'
    | '/seller/orders/'
    | '/seller/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  SearchRoute: typeof SearchRoute
  SellerRoute: typeof SellerRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  ProductsIdRoute: typeof ProductsIdRoute
  SubscriptionCallbackRoute: typeof SubscriptionCallbackRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/subscription/callback': {
      id: '/subscription/callback'
      path: '/subscription/callback'
      fullPath: '/subscription/callback'
      preLoaderRoute: typeof SubscriptionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/wallet': {
      id: '/seller/wallet'
      path: '/wallet'
      fullPath: '/seller/wallet'
      preLoaderRoute: typeof SellerWalletRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/subscription': {
      id: '/seller/subscription'
      path: '/subscription'
      fullPath: '/seller/subscription'
      preLoaderRoute: typeof SellerSubscriptionRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof SellerRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/seller/products/': {
      id: '/seller/products/'
      path: '/products'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof SellerProductsIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders/': {
      id: '/seller/orders/'
      path: '/orders'
      fullPath: '/seller/orders/'
      preLoaderRoute: typeof SellerOrdersIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products/new': {
      id: '/seller/products/new'
      path: '/products/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof SellerProductsNewRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products/$id': {
      id: '/seller/products/$id'
      path: '/products/$id'
      fullPath: '/seller/products/$id'
      preLoaderRoute: typeof SellerProductsIdRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders/$id': {
      id: '/seller/orders/$id'
      path: '/orders/$id'
      fullPath: '/seller/orders/$id'
      preLoaderRoute: typeof SellerOrdersIdRouteImport
      parentRoute: typeof SellerRoute
    }
    '/orders/status/$id': {
      id: '/orders/status/$id'
      path: '/status/$id'
      fullPath: '/orders/status/$id'
      preLoaderRoute: typeof OrdersStatusIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OrdersStatusIdRoute: typeof OrdersStatusIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OrdersStatusIdRoute: OrdersStatusIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface SellerRouteChildren {
  SellerProfileRoute: typeof SellerProfileRoute
  SellerSubscriptionRoute: typeof SellerSubscriptionRoute
  SellerWalletRoute: typeof SellerWalletRoute
  SellerIndexRoute: typeof SellerIndexRoute
  SellerOrdersIdRoute: typeof SellerOrdersIdRoute
  SellerProductsIdRoute: typeof SellerProductsIdRoute
  SellerProductsNewRoute: typeof SellerProductsNewRoute
  SellerOrdersIndexRoute: typeof SellerOrdersIndexRoute
  SellerProductsIndexRoute: typeof SellerProductsIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerProfileRoute: SellerProfileRoute,
  SellerSubscriptionRoute: SellerSubscriptionRoute,
  SellerWalletRoute: SellerWalletRoute,
  SellerIndexRoute: SellerIndexRoute,
  SellerOrdersIdRoute: SellerOrdersIdRoute,
  SellerProductsIdRoute: SellerProductsIdRoute,
  SellerProductsNewRoute: SellerProductsNewRoute,
  SellerOrdersIndexRoute: SellerOrdersIndexRoute,
  SellerProductsIndexRoute: SellerProductsIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  SearchRoute: SearchRoute,
  SellerRoute: SellerRouteWithChildren,
  WishlistRoute: WishlistRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  ProductsIdRoute: ProductsIdRoute,
  SubscriptionCallbackRoute: SubscriptionCallbackRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
